// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.SearchView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivitySearchBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final RecyclerView listaContactos;

  @NonNull
  public final SearchView txtBuscar;

  private ActivitySearchBinding(@NonNull LinearLayout rootView,
      @NonNull RecyclerView listaContactos, @NonNull SearchView txtBuscar) {
    this.rootView = rootView;
    this.listaContactos = listaContactos;
    this.txtBuscar = txtBuscar;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivitySearchBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivitySearchBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_search, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivitySearchBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.listaContactos;
      RecyclerView listaContactos = ViewBindings.findChildViewById(rootView, id);
      if (listaContactos == null) {
        break missingId;
      }

      id = R.id.txtBuscar;
      SearchView txtBuscar = ViewBindings.findChildViewById(rootView, id);
      if (txtBuscar == null) {
        break missingId;
      }

      return new ActivitySearchBinding((LinearLayout) rootView, listaContactos, txtBuscar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
