// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogAddTripAdminBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button addTripCancel;

  @NonNull
  public final Button addTripSubmit;

  @NonNull
  public final EditText newTripId;

  @NonNull
  public final EditText newTripName;

  private DialogAddTripAdminBinding(@NonNull LinearLayout rootView, @NonNull Button addTripCancel,
      @NonNull Button addTripSubmit, @NonNull EditText newTripId, @NonNull EditText newTripName) {
    this.rootView = rootView;
    this.addTripCancel = addTripCancel;
    this.addTripSubmit = addTripSubmit;
    this.newTripId = newTripId;
    this.newTripName = newTripName;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogAddTripAdminBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogAddTripAdminBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_add_trip_admin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogAddTripAdminBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.add_trip_cancel;
      Button addTripCancel = ViewBindings.findChildViewById(rootView, id);
      if (addTripCancel == null) {
        break missingId;
      }

      id = R.id.add_trip_submit;
      Button addTripSubmit = ViewBindings.findChildViewById(rootView, id);
      if (addTripSubmit == null) {
        break missingId;
      }

      id = R.id.new_trip_id;
      EditText newTripId = ViewBindings.findChildViewById(rootView, id);
      if (newTripId == null) {
        break missingId;
      }

      id = R.id.new_trip_name;
      EditText newTripName = ViewBindings.findChildViewById(rootView, id);
      if (newTripName == null) {
        break missingId;
      }

      return new DialogAddTripAdminBinding((LinearLayout) rootView, addTripCancel, addTripSubmit,
          newTripId, newTripName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
