// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DialogAddStopTimeAdminBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button cancel;

  @NonNull
  public final EditText newTime;

  @NonNull
  public final Button submit;

  @NonNull
  public final EditText tripId;

  private DialogAddStopTimeAdminBinding(@NonNull LinearLayout rootView, @NonNull Button cancel,
      @NonNull EditText newTime, @NonNull Button submit, @NonNull EditText tripId) {
    this.rootView = rootView;
    this.cancel = cancel;
    this.newTime = newTime;
    this.submit = submit;
    this.tripId = tripId;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DialogAddStopTimeAdminBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DialogAddStopTimeAdminBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.dialog_add_stop_time_admin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DialogAddStopTimeAdminBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cancel;
      Button cancel = ViewBindings.findChildViewById(rootView, id);
      if (cancel == null) {
        break missingId;
      }

      id = R.id.new_time;
      EditText newTime = ViewBindings.findChildViewById(rootView, id);
      if (newTime == null) {
        break missingId;
      }

      id = R.id.submit;
      Button submit = ViewBindings.findChildViewById(rootView, id);
      if (submit == null) {
        break missingId;
      }

      id = R.id.trip_id;
      EditText tripId = ViewBindings.findChildViewById(rootView, id);
      if (tripId == null) {
        break missingId;
      }

      return new DialogAddStopTimeAdminBinding((LinearLayout) rootView, cancel, newTime, submit,
          tripId);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
