// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import com.google.android.material.appbar.AppBarLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class DriverRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final TextView regDriver;

  @NonNull
  public final Button regDriverBtn;

  @NonNull
  public final EditText regDriverBusnumber;

  @NonNull
  public final EditText regDriverEnumber;

  @NonNull
  public final EditText regDriverName;

  @NonNull
  public final EditText regDriverPhone;

  @NonNull
  public final ImageView studentSignup;

  @NonNull
  public final Toolbar toolbar;

  private DriverRegisterBinding(@NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout, @NonNull TextView regDriver, @NonNull Button regDriverBtn,
      @NonNull EditText regDriverBusnumber, @NonNull EditText regDriverEnumber,
      @NonNull EditText regDriverName, @NonNull EditText regDriverPhone,
      @NonNull ImageView studentSignup, @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.regDriver = regDriver;
    this.regDriverBtn = regDriverBtn;
    this.regDriverBusnumber = regDriverBusnumber;
    this.regDriverEnumber = regDriverEnumber;
    this.regDriverName = regDriverName;
    this.regDriverPhone = regDriverPhone;
    this.studentSignup = studentSignup;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DriverRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DriverRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.driver_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DriverRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.reg_driver;
      TextView regDriver = ViewBindings.findChildViewById(rootView, id);
      if (regDriver == null) {
        break missingId;
      }

      id = R.id.reg_driver_btn;
      Button regDriverBtn = ViewBindings.findChildViewById(rootView, id);
      if (regDriverBtn == null) {
        break missingId;
      }

      id = R.id.reg_driver_busnumber;
      EditText regDriverBusnumber = ViewBindings.findChildViewById(rootView, id);
      if (regDriverBusnumber == null) {
        break missingId;
      }

      id = R.id.reg_driver_enumber;
      EditText regDriverEnumber = ViewBindings.findChildViewById(rootView, id);
      if (regDriverEnumber == null) {
        break missingId;
      }

      id = R.id.reg_driver_name;
      EditText regDriverName = ViewBindings.findChildViewById(rootView, id);
      if (regDriverName == null) {
        break missingId;
      }

      id = R.id.reg_driver_phone;
      EditText regDriverPhone = ViewBindings.findChildViewById(rootView, id);
      if (regDriverPhone == null) {
        break missingId;
      }

      id = R.id.student_signup;
      ImageView studentSignup = ViewBindings.findChildViewById(rootView, id);
      if (studentSignup == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new DriverRegisterBinding((ConstraintLayout) rootView, appBarLayout, regDriver,
          regDriverBtn, regDriverBusnumber, regDriverEnumber, regDriverName, regDriverPhone,
          studentSignup, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
