// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemRegionsAdminBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView delRegionNameAdmin;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final TextView searchRegionNameAdmin;

  private ListItemRegionsAdminBinding(@NonNull RelativeLayout rootView,
      @NonNull ImageView delRegionNameAdmin, @NonNull ImageView imageView,
      @NonNull TextView searchRegionNameAdmin) {
    this.rootView = rootView;
    this.delRegionNameAdmin = delRegionNameAdmin;
    this.imageView = imageView;
    this.searchRegionNameAdmin = searchRegionNameAdmin;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemRegionsAdminBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemRegionsAdminBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_regions_admin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemRegionsAdminBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.del_region_name_admin;
      ImageView delRegionNameAdmin = ViewBindings.findChildViewById(rootView, id);
      if (delRegionNameAdmin == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.search_region_name_admin;
      TextView searchRegionNameAdmin = ViewBindings.findChildViewById(rootView, id);
      if (searchRegionNameAdmin == null) {
        break missingId;
      }

      return new ListItemRegionsAdminBinding((RelativeLayout) rootView, delRegionNameAdmin,
          imageView, searchRegionNameAdmin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
