// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemStudentsBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final TextView viewCorreo;

  @NonNull
  public final TextView viewNombre;

  @NonNull
  public final TextView viewTelefono;

  private ListItemStudentsBinding(@NonNull RelativeLayout rootView, @NonNull ImageView imageView,
      @NonNull TextView viewCorreo, @NonNull TextView viewNombre, @NonNull TextView viewTelefono) {
    this.rootView = rootView;
    this.imageView = imageView;
    this.viewCorreo = viewCorreo;
    this.viewNombre = viewNombre;
    this.viewTelefono = viewTelefono;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemStudentsBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemStudentsBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_students, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemStudentsBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.viewCorreo;
      TextView viewCorreo = ViewBindings.findChildViewById(rootView, id);
      if (viewCorreo == null) {
        break missingId;
      }

      id = R.id.viewNombre;
      TextView viewNombre = ViewBindings.findChildViewById(rootView, id);
      if (viewNombre == null) {
        break missingId;
      }

      id = R.id.viewTelefono;
      TextView viewTelefono = ViewBindings.findChildViewById(rootView, id);
      if (viewTelefono == null) {
        break missingId;
      }

      return new ListItemStudentsBinding((RelativeLayout) rootView, imageView, viewCorreo,
          viewNombre, viewTelefono);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
