// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import com.google.android.material.appbar.AppBarLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SigninStudentBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button SSignin;

  @NonNull
  public final TextView SignUpButton;

  @NonNull
  public final TextView StudentSigninPage;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final ImageView studentLogin;

  @NonNull
  public final EditText studentNumber;

  @NonNull
  public final EditText studentPassword;

  @NonNull
  public final Toolbar toolbar;

  private SigninStudentBinding(@NonNull ConstraintLayout rootView, @NonNull Button SSignin,
      @NonNull TextView SignUpButton, @NonNull TextView StudentSigninPage,
      @NonNull AppBarLayout appBarLayout, @NonNull ImageView studentLogin,
      @NonNull EditText studentNumber, @NonNull EditText studentPassword,
      @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.SSignin = SSignin;
    this.SignUpButton = SignUpButton;
    this.StudentSigninPage = StudentSigninPage;
    this.appBarLayout = appBarLayout;
    this.studentLogin = studentLogin;
    this.studentNumber = studentNumber;
    this.studentPassword = studentPassword;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SigninStudentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SigninStudentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.signin_student, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SigninStudentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.S_Signin;
      Button SSignin = ViewBindings.findChildViewById(rootView, id);
      if (SSignin == null) {
        break missingId;
      }

      id = R.id.SignUpButton;
      TextView SignUpButton = ViewBindings.findChildViewById(rootView, id);
      if (SignUpButton == null) {
        break missingId;
      }

      id = R.id.StudentSigninPage;
      TextView StudentSigninPage = ViewBindings.findChildViewById(rootView, id);
      if (StudentSigninPage == null) {
        break missingId;
      }

      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.student_login;
      ImageView studentLogin = ViewBindings.findChildViewById(rootView, id);
      if (studentLogin == null) {
        break missingId;
      }

      id = R.id.student_number;
      EditText studentNumber = ViewBindings.findChildViewById(rootView, id);
      if (studentNumber == null) {
        break missingId;
      }

      id = R.id.student_password;
      EditText studentPassword = ViewBindings.findChildViewById(rootView, id);
      if (studentPassword == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new SigninStudentBinding((ConstraintLayout) rootView, SSignin, SignUpButton,
          StudentSigninPage, appBarLayout, studentLogin, studentNumber, studentPassword, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
