// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SigninAdminBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView StudentSigninPage;

  @NonNull
  public final EditText adminPassword;

  @NonNull
  public final Button adminSignin;

  @NonNull
  public final EditText adminUserName;

  @NonNull
  public final ImageView studentLogin;

  private SigninAdminBinding(@NonNull ConstraintLayout rootView,
      @NonNull TextView StudentSigninPage, @NonNull EditText adminPassword,
      @NonNull Button adminSignin, @NonNull EditText adminUserName,
      @NonNull ImageView studentLogin) {
    this.rootView = rootView;
    this.StudentSigninPage = StudentSigninPage;
    this.adminPassword = adminPassword;
    this.adminSignin = adminSignin;
    this.adminUserName = adminUserName;
    this.studentLogin = studentLogin;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SigninAdminBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SigninAdminBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.signin_admin, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SigninAdminBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.StudentSigninPage;
      TextView StudentSigninPage = ViewBindings.findChildViewById(rootView, id);
      if (StudentSigninPage == null) {
        break missingId;
      }

      id = R.id.admin_password;
      EditText adminPassword = ViewBindings.findChildViewById(rootView, id);
      if (adminPassword == null) {
        break missingId;
      }

      id = R.id.admin_signin;
      Button adminSignin = ViewBindings.findChildViewById(rootView, id);
      if (adminSignin == null) {
        break missingId;
      }

      id = R.id.admin_user_name;
      EditText adminUserName = ViewBindings.findChildViewById(rootView, id);
      if (adminUserName == null) {
        break missingId;
      }

      id = R.id.student_login;
      ImageView studentLogin = ViewBindings.findChildViewById(rootView, id);
      if (studentLogin == null) {
        break missingId;
      }

      return new SigninAdminBinding((ConstraintLayout) rootView, StudentSigninPage, adminPassword,
          adminSignin, adminUserName, studentLogin);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
