// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import com.google.android.material.appbar.AppBarLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SignupStudentBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button SSignup;

  @NonNull
  public final TextView StudentSignUpPage;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final EditText sNumber;

  @NonNull
  public final EditText studentAddress;

  @NonNull
  public final EditText studentDept;

  @NonNull
  public final EditText studentEmail;

  @NonNull
  public final EditText studentName;

  @NonNull
  public final EditText studentPassword;

  @NonNull
  public final EditText studentPhone;

  @NonNull
  public final ImageView studentSignup;

  @NonNull
  public final Toolbar toolbar;

  private SignupStudentBinding(@NonNull ConstraintLayout rootView, @NonNull Button SSignup,
      @NonNull TextView StudentSignUpPage, @NonNull AppBarLayout appBarLayout,
      @NonNull EditText sNumber, @NonNull EditText studentAddress, @NonNull EditText studentDept,
      @NonNull EditText studentEmail, @NonNull EditText studentName,
      @NonNull EditText studentPassword, @NonNull EditText studentPhone,
      @NonNull ImageView studentSignup, @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.SSignup = SSignup;
    this.StudentSignUpPage = StudentSignUpPage;
    this.appBarLayout = appBarLayout;
    this.sNumber = sNumber;
    this.studentAddress = studentAddress;
    this.studentDept = studentDept;
    this.studentEmail = studentEmail;
    this.studentName = studentName;
    this.studentPassword = studentPassword;
    this.studentPhone = studentPhone;
    this.studentSignup = studentSignup;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SignupStudentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SignupStudentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.signup_student, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SignupStudentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.S_Signup;
      Button SSignup = ViewBindings.findChildViewById(rootView, id);
      if (SSignup == null) {
        break missingId;
      }

      id = R.id.StudentSignUpPage;
      TextView StudentSignUpPage = ViewBindings.findChildViewById(rootView, id);
      if (StudentSignUpPage == null) {
        break missingId;
      }

      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.sNumber;
      EditText sNumber = ViewBindings.findChildViewById(rootView, id);
      if (sNumber == null) {
        break missingId;
      }

      id = R.id.student_address;
      EditText studentAddress = ViewBindings.findChildViewById(rootView, id);
      if (studentAddress == null) {
        break missingId;
      }

      id = R.id.student_dept;
      EditText studentDept = ViewBindings.findChildViewById(rootView, id);
      if (studentDept == null) {
        break missingId;
      }

      id = R.id.student_email;
      EditText studentEmail = ViewBindings.findChildViewById(rootView, id);
      if (studentEmail == null) {
        break missingId;
      }

      id = R.id.student_name;
      EditText studentName = ViewBindings.findChildViewById(rootView, id);
      if (studentName == null) {
        break missingId;
      }

      id = R.id.student_password;
      EditText studentPassword = ViewBindings.findChildViewById(rootView, id);
      if (studentPassword == null) {
        break missingId;
      }

      id = R.id.student_phone;
      EditText studentPhone = ViewBindings.findChildViewById(rootView, id);
      if (studentPhone == null) {
        break missingId;
      }

      id = R.id.student_signup;
      ImageView studentSignup = ViewBindings.findChildViewById(rootView, id);
      if (studentSignup == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new SignupStudentBinding((ConstraintLayout) rootView, SSignup, StudentSignUpPage,
          appBarLayout, sNumber, studentAddress, studentDept, studentEmail, studentName,
          studentPassword, studentPhone, studentSignup, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
