// Generated by view binder compiler. Do not edit!
package com.aau.trakio.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.Toolbar;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.aau.trakio.R;
import com.google.android.material.appbar.AppBarLayout;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class SigninDriverBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button DSignin;

  @NonNull
  public final EditText DriverNumber;

  @NonNull
  public final TextView DriverSigninPage;

  @NonNull
  public final AppBarLayout appBarLayout;

  @NonNull
  public final ImageView imageView;

  @NonNull
  public final Toolbar toolbar;

  private SigninDriverBinding(@NonNull ConstraintLayout rootView, @NonNull Button DSignin,
      @NonNull EditText DriverNumber, @NonNull TextView DriverSigninPage,
      @NonNull AppBarLayout appBarLayout, @NonNull ImageView imageView, @NonNull Toolbar toolbar) {
    this.rootView = rootView;
    this.DSignin = DSignin;
    this.DriverNumber = DriverNumber;
    this.DriverSigninPage = DriverSigninPage;
    this.appBarLayout = appBarLayout;
    this.imageView = imageView;
    this.toolbar = toolbar;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static SigninDriverBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static SigninDriverBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.signin_driver, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static SigninDriverBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.D_Signin;
      Button DSignin = ViewBindings.findChildViewById(rootView, id);
      if (DSignin == null) {
        break missingId;
      }

      id = R.id.Driver_Number;
      EditText DriverNumber = ViewBindings.findChildViewById(rootView, id);
      if (DriverNumber == null) {
        break missingId;
      }

      id = R.id.DriverSigninPage;
      TextView DriverSigninPage = ViewBindings.findChildViewById(rootView, id);
      if (DriverSigninPage == null) {
        break missingId;
      }

      id = R.id.appBarLayout;
      AppBarLayout appBarLayout = ViewBindings.findChildViewById(rootView, id);
      if (appBarLayout == null) {
        break missingId;
      }

      id = R.id.imageView;
      ImageView imageView = ViewBindings.findChildViewById(rootView, id);
      if (imageView == null) {
        break missingId;
      }

      id = R.id.toolbar;
      Toolbar toolbar = ViewBindings.findChildViewById(rootView, id);
      if (toolbar == null) {
        break missingId;
      }

      return new SigninDriverBinding((ConstraintLayout) rootView, DSignin, DriverNumber,
          DriverSigninPage, appBarLayout, imageView, toolbar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
